name: video-downloader-flask
services:
  - name: web
    type: web
    env:
      - key: PORT
        value: "8000"
    build:
      builder: heroku/buildpacks:20
    run:
      cmd: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
